---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: linuxserver/bazarr
      tag: 1.2.3
    env:
      TZ: ${TIMEZONE}
      POSTGRES_ENABLED: true
      POSTGRES_HOST: postgresql.database.svc.cluster.local
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: bazarr
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ${SECRET_POSTGRES_ADMIN_PASS}
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Bazarr
          hajimari.io/icon: dashicons:text
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      media:
        enabled: true
        mountPath: /media
        path: "${STORAGE_NAS_MEDIA_PATH}"
        server: "${STORAGE_NAS_IP}"
        type: nfs
