---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - release.yaml
configMapGenerator:
  - name: cloudflare-ddns-configmap
    files:
      - ./cloudflare-ddns.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
