apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: networking
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sA2rWqIeHoSnFEFjeLxbOxi68kkQv6ExyFAw+Q==,iv:eNWjMykPIwm2CMv7vNP4FOcSn/YoZ0fnh//+sRmZst8=,tag:j0p/dXF1sDtgKv4fyV3/8Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:FFN6jpVGBevwID7Ll5xXhZ/59TL0aiVoq0AulNVSz/1EXZ7OpA==,iv:wfVaaPj8Did2TXHTXrFn6PdlrVZt2JU3yeBEcZpJvTE=,tag:yCnZ8wiZAm/0LwVbMhXfig==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:YR5QCWEJ7GsU9Fa+CtgGDPJJJA==,iv:2GXrkOwT6se7l3bXVHR4Gz0lfiUujWuhShCM4INmgqg=,tag:+/tzcHPecs0z2AidO/YVwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNlowaEtHMXZjcHQrZ0ZR
            bWFwM250L1FQYTBMZk9DQS9tQ2xLR1d5aTFRCmVxN3FrSUZ1VlVZMWRzUFo3aHRx
            Z1RtOTN4MXNmQXBrMXE4VEM5cEt1bUUKLS0tICtuUHRuSzNOMzVhc1kzOHVPc1g1
            U3hWUnZrb090QjR2NkRidjlhYVpKTDQKNOFAc0j+fm1ONvPYQw5fUCwIOymUDeWL
            pZ0kQy1MHeOiwnP7eEDUaHVdfOe7bx1dSh9aJCjZXc9FfiuRxbEZ2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T00:07:59Z"
    mac: ENC[AES256_GCM,data:Y4HYdanpsP0+HM9UEBCyfArNCiEF4DUIc6tFvJnwLCQnxHtJ1Dgil0HSM7WdD/htAlHJ287J1AOBjMj2Ox37U+8OUtMLv10fVe+YjIdLRA0V/YZEJwl2A8Zcr2v2i33H1ZY3Szy16LOfgIQwk3ZSthwZ9UT2p5EmHcjKSgX032Q=,iv:87HM0xjpGaC4u1oM5rm5JFGimyb86eA32/483ZpyFnY=,tag:oQ1Io1/aTfPks6NDt7HtYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
