---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: randomninjaatk/lidarr-extended
      tag: latest
    hostname: lidarr
    env:
      TZ: ${TIMEZONE}
      PUID: 1000
      PGID: 1000
      enableAudioScript: true
      enableVideoScript: false
      configureLidarrWithOptimalSettings: true
      audioFormat: native
      audioBitrate: high
      requireQuality: true
      enableReplaygainTags: true
      audioLyricType: both
      dlClientSource: deezer
      arlToken: ${SECRET_DEEZER_ARL}
      lidarrSearchForMissing: true
      enableBeetsTagging: true
      beetsMatchPercentage: 90
    service:
      main:
        ports:
          http:
            port: 8686
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/appName: Lidarr
          hajimari.io/icon: icon-park-solid:headphone-sound
        hosts:
          - host: &host "lidarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config
      media:
        enabled: true
        mountPath: /media
        path: "${STORAGE_NAS_MEDIA_PATH}"
        server: "${STORAGE_NAS_IP}"
        type: nfs
