---
# Used by label sync action to create labels automatically
# Areas
- name: area/ansible
  color: "72ccf3"
  description: "Changes made in the ansible directory"
- name: area/github
  color: "72ccf3"
  description: "Changes made in the github directory"
- name: area/cluster
  color: "72ccf3"
  description: "Changes made in the cluster directory"
- name: area/terraform
  color: "72ccf3"
  description: "Changes made in the terraform directory"
# Renovate
- name: renovate/ansible
  color: "ffc300"
- name: renovate/container
  color: "ffc300"
- name: renovate/github-action
  color: "ffc300"
- name: renovate/github-release
  color: "ffc300"
- name: renovate/helm
  color: "ffc300"
- name: renovate/terraform
  color: "ffc300"
# Semantic Type
- name: type/patch
  color: "FFEC19"
- name: type/minor
  color: "FF9800"
- name: type/major
  color: "F6412D"
- name: type/break
  color: "F6412D"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
