---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord-provider
  namespace: flux-system
spec:
  type: discord
  secretRef:
    name: SECRET_FLUX_DISCORD_WEBHOOK
