---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recyclarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "@daily"
        ttlSecondsAfterFinished: 86400
    restartPolicy: OnFailure
    image:
      repository: ghcr.io/recyclarr/recyclarr
      tag: 5.2.1
    command: ["/app/recyclarr/recyclarr"]
    args: ["sync"]
    env:
      TZ: "${TIMEZONE}"
    envFrom:
      - secretRef:
          name: sonarr-apikey
      - secretRef:
          name: radarr-apikey
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: configMap
        name: recyclarr-configmap
        subPath: recyclarr.yml
        mountPath: /config/recyclarr.yml
        defaultMode: 0775
        readOnly: true
