---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: chart-fairwinds
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Goldilocks
          hajimari.io/icon: mdi:align-vertical-top
          nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/23
        hosts:
          - host: &host goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
      resources:
        requests:
          cpu: 15m
          memory: 105M
