---
cluster:
  children:
    master:
      hosts:
        master-0:
          ansible_host: 192.168.0.210
        master-1:
          ansible_host: 192.168.0.211
        master-2:
          ansible_host: 192.168.0.212
    worker:
      hosts:
        worker-3:
          ansible_host: 192.168.0.220
        worker-4:
          ansible_host: 192.168.0.221
