---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: fallenbagel/jellyseerr
      tag: 1.7.0
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 5055
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Jellyseerr
          hajimari.io/icon: bi:eye-fill
          external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"
        hosts:
          - host: &host "requests.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: jellyseerr-config
        mountPath: /app/config

    hostAliases:
      - ip: 192.168.0.228
        hostnames:
          - stream.${SECRET_DOMAIN}
