apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T18:27:07Z"
    mac: ENC[AES256_GCM,data:wak+evYkVnhr6KFc5qbYufa7zh5xlcqkYjEuFfh9K44DEB+4h3PxrfCqY2Ffcah7gtyKgYmEcqgpCKkRVmkZNUhKIV1ZJIVFbQDqVlCzn30lVmZmzyoMVn6dYTR6DiczGzpnBNV7aoEZyyaWsOPgdSj9YK08fBf2BX2Q9DrH8vU=,iv:hdnFtfG4NEiENPp6kr+45xe9vjXLWt4gZMA7qrOgHHU=,tag:NihD4uWRoRRUcQgW/tSu+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
