apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_LAN_DOMAIN: ENC[AES256_GCM,data:fre3lidfrgYrdwVaMA==,iv:s8tKA+NBQUkrot0Ug7YL8uCsgpQWGkkLVxdg74S3rkw=,tag:gg8+yUI4NbRGjhH+Az7vQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-19T21:36:32Z"
    mac: ENC[AES256_GCM,data:iOrvlfZDkyKWnnJn51bGKdkWKVS7LXAZAcrCwOWZcGmWtm6nCDNHoJtnz+SOaq36yYma9Rq4NU2mp9OaguMnHmszEJsrie+3/ytOqJ3od8KMORYqpEV8C7s0aUFCN3gD1X7fU3Pv7SUY6Ad7HJz/LpupqdPTfGLcpdJOrcLLKOo=,iv:+R1pzzn/QQcN7f/icEt2yBpHXCXops5pKwkbiKmUi6Q=,tag:avFEXgKSVSKwfLdXizhXcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
