apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media,database
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wPV8ljIqql0=,iv:F7SUSRpvP98hC7vr01eEplIaNCPvcWcTPjZEE58qDq4=,tag:2SbjaGXLBxeFBAS/rJvN9w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:l3e3hVLZ0u0KEhveClfrTX7q6BK4j0+QN9orhIcy4J5TuX7A4g==,iv:YOPO0AmRSsJ+MpuZT8PxfJRZa4AiUERi918iEiCXxek=,tag:f5x0udKPrsyLVDb0NBoY4w==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:IWuRs1BiECn1jQ5QZg==,iv:tzCGN2rGpdE0UtshFiPflEVXYk/eTSCxAaPEHQCg66k=,tag:fKocOZufXOHgHDXDu7lrIQ==,type:str]
    SECRET_PROM_DISCORD_WH_URL: ENC[AES256_GCM,data:PtHo0dXGambeqRZhYLYtWk5bHngv2rG5W4EvcuIZccJIE4vBLmsxGDryZnvnnIKC2W5iHNTOEnH97Cx06MOH2D4ye8gvWjouQ9rWwVkjvKQcE4JXA1J9i9dRtFGb6/qg9p8vcyg3Xz9ci/6ETzkt19e+pIxVptSRYg==,iv:U079IdOLfg7k/dI4yEZJKTQvgPEh1EPnHiDh6vfKQyM=,tag:BN7VTJmKywN2nbgS1Sxdvg==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:OzTef8Y7UVY5A41K5qlb,iv:NDwqXdgCXzpInd9ZIqQ3iSb0RZDgjEKNyeHaiVtRUAo=,tag:9g0RhSiq6J/ITNriNJ21pg==,type:str]
    SECRET_INFLUXDB_ADMIN_PASS: ENC[AES256_GCM,data:DeQCIqD4BkCQIbMdyGv/NC2/,iv:1jn0HeaolqLUUqZEkSwyVvwfZ0yFRYYA7mkQwXyiwag=,tag:UyZuQC3tL0/sx4EFFympKw==,type:str]
    SECRET_INFLUXDB_ADMIN_TOKEN: ENC[AES256_GCM,data:TSW8u+DIUmFIisZRJ8pWeb+8PqjAaYGkKaU=,iv:NsJvRo+rHKAy07F/a5TDjHkZrUlUAU+Z59i/98siuEU=,tag:RWEwmdUcXzXls5R94Liw8w==,type:str]
    #ENC[AES256_GCM,data:g88t/FIdrMu0GhNO/Bw=,iv:m2EGst+uL0nKMtWTqRfxcciCpGWrKNsC3FBCtmTurog=,tag:WexHqYux1Hy9pqhTXYTegA==,type:comment]
    GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:gKxtFkjQ,iv:EMVqpFmzt4KSUK63ywQccNfvEZLEqA4mfNqO3fe1YYk=,tag:NSfj0XHSQgwJX5KOA1xe6w==,type:str]
    GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:oshXbVETlBG191zSez66VTrEEFbbCIHpUFnR4VtESoRs5qkk8iZOhw==,iv:Smu/bNSAn12kbXb7wSm2yIyMLH7LbrsakXOpEAESNFY=,tag:BFzTcHODjHSxaMI+7Hxjog==,type:str]
    #ENC[AES256_GCM,data:F54YNpQW4LlTuYaFby5SeuR7,iv:2C8XP+yYfZyolfGs93KzdQsVEjfUrFHhfJKxsnT/jKo=,tag:fW7+LjbpM2V36G187f+4uA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6LvBnJRgumB5V/T9A+4z9lg5qq8vmY1E4kuXbvFiF4JLNpM7lOD3hv6IUUbzjKnfIpc=,iv:2GfnnoHEakxyfqu0IGugwhZxyJI7hunrUML4WFZf2iQ=,tag:DG90bI8qST63S3mb1TKv2Q==,type:str]
    AUTHENTIK_EMAIL_HOST: ENC[AES256_GCM,data:al3cABGaTbpcg5CxlbLBKmR65CU=,iv:iioJvXG5k5qyH/D7DuPu8BlpdRzQDQkdLbYNaZxkfEY=,tag:0gU6/eDHcPKapCHC9O4yaw==,type:str]
    AUTHENTIK_EMAIL_PORT: ENC[AES256_GCM,data:qIrU,iv:eXboJJg9FyoblMQ1RzdxUz1pRIjfuTESFA6qFM4dwX8=,tag:tl03FU/glZhhbvJuWfe/cQ==,type:str]
    AUTHENTIK_EMAIL_USERNAME: ENC[AES256_GCM,data:RK8EQngKZQhETMSew3SGXlc0YfkZvgo=,iv:UEsC8yQ3Z2w25EFwvonRVUlwfMb2Jf5iVjZOLs7jrUQ=,tag:rZ/fZahR6r/9aqJoNObpGQ==,type:str]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:FPuN0wLolxY5KPrWP5Qr3wOH,iv:3vrd3BPDjjJTrnmdPhAuZTZWT8ypCi90wd4a/g97EdQ=,tag:QK/njioNj4AXvMAJD6iufA==,type:str]
    AUTHENTIK_EMAIL_USE_TLS: ENC[AES256_GCM,data:nqq3f+E=,iv:OpEXDvkmvZUOgUIXrxFm2kTBgkDOsQyfDcEB6pEqYto=,tag:qSMnyY0Nn/7M5cIle43IRw==,type:str]
    AUTHENTIK_EMAIL_USE_SSL: ENC[AES256_GCM,data:766qiw==,iv:X5zlu7fd7/ayql/5niS67OZBnyYodsxRXzBMxJOhAME=,tag:fZi149cv1VOQmgDZVgF48w==,type:str]
    AUTHENTIK_EMAIL_TIMEOUT: ENC[AES256_GCM,data:xvU=,iv:7ll8kcP/7KrXyVdcCisQ6RMDsEZyUBE49WI0iAdAokQ=,tag:zAFT0YhpoN7FXJT8nTTXDw==,type:str]
    AUTHENTIK_EMAIL_FROM: ENC[AES256_GCM,data:p4ErG91RR25PtKDRKQD5mJfFM+mHts8=,iv:8ZY1C2i9YDqeitU/u5IFHCmhn+miDoo92Ptl5qJQ7xM=,tag:aANleWoG4m2jovgGMdRSGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T04:23:16Z"
    mac: ENC[AES256_GCM,data:wDLkBSBJ014m5GwJaPmD7UOBuLfUB577BtiUW42AYkMF4ivvN6bqQOQky5M+YFuz+EekS256xKvznGc8gYNM9eFmOpSktjAAgO+oIlpmOvvm+dnt3wDegQqQ+q51beTaVOrKr455T8KpKzdNKh0yJYl3lXGjeonpauCffI0p2pI=,iv:cNhOuR2LpEDxRGmfoj9LDRcj954ttliuLIavi6h8qc0=,tag:8ZxUoT4NFhyJ5lk4LPsFMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
