apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_LAN_DOMAIN: ENC[AES256_GCM,data:fre3lidfrgYrdwVaMA==,iv:s8tKA+NBQUkrot0Ug7YL8uCsgpQWGkkLVxdg74S3rkw=,tag:gg8+yUI4NbRGjhH+Az7vQA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
    SECRET_PROM_DISCORD_WH_URL: ENC[AES256_GCM,data:PtHo0dXGambeqRZhYLYtWk5bHngv2rG5W4EvcuIZccJIE4vBLmsxGDryZnvnnIKC2W5iHNTOEnH97Cx06MOH2D4ye8gvWjouQ9rWwVkjvKQcE4JXA1J9i9dRtFGb6/qg9p8vcyg3Xz9ci/6ETzkt19e+pIxVptSRYg==,iv:U079IdOLfg7k/dI4yEZJKTQvgPEh1EPnHiDh6vfKQyM=,tag:BN7VTJmKywN2nbgS1Sxdvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T00:04:27Z"
    mac: ENC[AES256_GCM,data:YPjpsip8QgB3GZOCpmytjfPN1eKHWztGC7Uentk8Nxk8WpzVUywwnd9XK+WtHFV8qIpbFYCx8TdvSvKvqvuS7PSKNw9i9B235Y8HIIwpkeDTozCpaWnoK9lJ6CuFjvLYI0z7lUEaB1Qj/pcnyYi0GEDJABQNagmp+em8ws+haTA=,iv:XxYx8BTry+7wbVusTiYoqfzYNBqHBdi7nGxggjo9XDU=,tag:mAfPZwWghlZryeOUn1462g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
