apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
    SECRET_FLUX_DISCORD_WEBHOOK: ENC[AES256_GCM,data:KbEPtzIUYwDnDvN8VGaL4yRQdr7mBEx/KzjPzrqjvpIMpfKAt3JobNEy3ZKMAfhQz/D7LeICeVYz/FochmutA3OCw4Hehdd3UKNLlmL/e01rujAfmEInSQa9YHCxr6SJ2nLfMB93G9snH3datbYbGTtwfow2Q9NKXg==,iv:CmIOy5X4WSDSpaciABaCREnQ0n6dVGU8YmvH0mQ2Txo=,tag:tyT3Qk7fxyiVmFVFv9AwIQ==,type:str]
    SECRET_GH_TOKEN: ENC[AES256_GCM,data:vi6QUfRCvLcgq/DKrp8bLXgBtIxF2AwGDRY0vmjI0d+J6KpN7m92rw==,iv:jatG3LFuSrGXuSpbsefJl5ypru/9OoufmAvLSrwR5Y8=,tag:NvM3GZm+IwxPYx0b3BipSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-17T16:21:57Z"
    mac: ENC[AES256_GCM,data:FnkfyRf2dZC92crdiEX/1YvBxQGMoIMSLXtElAytamH+Rsl3paqJJq7kFmpLQM9E/8ul+xgqOmMR6fttO2sRBSGwTdDGlxqy8hlJGm7OilvCi3+NJAtAF9JadzMU6Wz4hMGc9upECA6FJ+KqMg/F/VH/bZa4K5387GsFIBkIgck=,iv:An3q0i41OldtQdf2ZYuAi4d7hsPgNkGsEB5MekiXCUk=,tag:Lfs4VPdnPz65x5HMrtUaUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
