apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:l3e3hVLZ0u0KEhveClfrTX7q6BK4j0+QN9orhIcy4J5TuX7A4g==,iv:YOPO0AmRSsJ+MpuZT8PxfJRZa4AiUERi918iEiCXxek=,tag:f5x0udKPrsyLVDb0NBoY4w==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:NohLZknSEckR1pgQoNQTWfXqkA==,iv:3QvYKWc2vqWJCbdf0gbCcAvSvrrN6mHjFPMThav0DLg=,tag:L4puJ7bND4/KqUgi8ONphg==,type:str]
    SECRET_PROM_DISCORD_WH_URL: ENC[AES256_GCM,data:PtHo0dXGambeqRZhYLYtWk5bHngv2rG5W4EvcuIZccJIE4vBLmsxGDryZnvnnIKC2W5iHNTOEnH97Cx06MOH2D4ye8gvWjouQ9rWwVkjvKQcE4JXA1J9i9dRtFGb6/qg9p8vcyg3Xz9ci/6ETzkt19e+pIxVptSRYg==,iv:U079IdOLfg7k/dI4yEZJKTQvgPEh1EPnHiDh6vfKQyM=,tag:BN7VTJmKywN2nbgS1Sxdvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T22:09:28Z"
    mac: ENC[AES256_GCM,data:KneLeUXeq9+0H+ewwmvka3EtI3jWQXfT9nejGjgCiq9kr5xJwUa3UOJKUvBgV/n9SezFIxUoUQ2CHRuU4hmdDFGZqpw44Uk6GL4o/CyWCqHFRMVXwtQOha2DAlnWyGiyaK6vMGWocIMMA5tmk0V2Lkev1bHhFWaPNU1hjp65YMY=,iv:5Yskig1XRL+ZOJLv0K/wf6oO8cwKiYeK7TdtCndgx5M=,tag:G9XWXKAQ15P4vhrDHx8sdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
