---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Bucharest
  METALLB_LB_RANGE: "192.168.1.200-192.168.1.250"
  NIGNX_INGRESS_IP: "192.168.1.222"
  K8S_GATEWAY_IP: "192.168.1.200"
  STORAGE_NAS_IP: "192.168.0.111"
  STORAGE_NAS_MEDIA_PATH: "/volume1/media"
