apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: default,networking,cert-manager,kube-system,media,database
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ARcPV/8ozoxO5r48tqE=,iv:qRfqXndxF9HR4ngGYgZhfqtj/SmSD4r6oxqjlTUocfk=,tag:yR0GgOmCmAPZb2B57oJQcQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cfHqVx8FKp8x6qDVN5uK8ntI5df4SWmNU65v4A==,iv:L9Z2ATCAOTioDlqv0jqy+ktwq60UNx3kuXTkRzzF2gM=,tag:eelr6azYKNEAvbMyISZU3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:l3e3hVLZ0u0KEhveClfrTX7q6BK4j0+QN9orhIcy4J5TuX7A4g==,iv:YOPO0AmRSsJ+MpuZT8PxfJRZa4AiUERi918iEiCXxek=,tag:f5x0udKPrsyLVDb0NBoY4w==,type:str]
    CLOUDFLARE_DDNS_RECORD: ENC[AES256_GCM,data:NohLZknSEckR1pgQoNQTWfXqkA==,iv:3QvYKWc2vqWJCbdf0gbCcAvSvrrN6mHjFPMThav0DLg=,tag:L4puJ7bND4/KqUgi8ONphg==,type:str]
    SECRET_PROM_DISCORD_WH_URL: ENC[AES256_GCM,data:PtHo0dXGambeqRZhYLYtWk5bHngv2rG5W4EvcuIZccJIE4vBLmsxGDryZnvnnIKC2W5iHNTOEnH97Cx06MOH2D4ye8gvWjouQ9rWwVkjvKQcE4JXA1J9i9dRtFGb6/qg9p8vcyg3Xz9ci/6ETzkt19e+pIxVptSRYg==,iv:U079IdOLfg7k/dI4yEZJKTQvgPEh1EPnHiDh6vfKQyM=,tag:BN7VTJmKywN2nbgS1Sxdvg==,type:str]
    SECRET_POSTGRES_ADMIN_PASS: ENC[AES256_GCM,data:OzTef8Y7UVY5A41K5qlb,iv:NDwqXdgCXzpInd9ZIqQ3iSb0RZDgjEKNyeHaiVtRUAo=,tag:9g0RhSiq6J/ITNriNJ21pg==,type:str]
    SECRET_DEEZER_ARL: ENC[AES256_GCM,data:4JqSkH7Q24ee8S6D8i4klPiwZoVAZZLN054uVF9OSGWdBM6y9/PBq0bquemdaCiEuoYlzDBvXezr2jTwmUfz+QG6WXVkKLUBLqj7Md/8QTu/onu3DZL9AutOWD0DggsJ8mOzdVegkPH9FFGCSKPa8GDF3IiO6wWriqn0YqZTqiyVgp020bVa2HgRyG9S1nDL6kq/b0cWl+kdyg7Kl6jILmH2ozgo2e/hbdGBAFPjssMh9MGXbSPcFf8KA/15kzcG,iv:fr2N/fEEYNLB8/9eb3WqN7mJdRC4y5a8cGpfWm1xpIU=,tag:4l0WdYMWNYapWm2c7xEKsQ==,type:str]
    #ENC[AES256_GCM,data:g88t/FIdrMu0GhNO/Bw=,iv:m2EGst+uL0nKMtWTqRfxcciCpGWrKNsC3FBCtmTurog=,tag:WexHqYux1Hy9pqhTXYTegA==,type:comment]
    GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:gKxtFkjQ,iv:EMVqpFmzt4KSUK63ywQccNfvEZLEqA4mfNqO3fe1YYk=,tag:NSfj0XHSQgwJX5KOA1xe6w==,type:str]
    GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:oshXbVETlBG191zSez66VTrEEFbbCIHpUFnR4VtESoRs5qkk8iZOhw==,iv:Smu/bNSAn12kbXb7wSm2yIyMLH7LbrsakXOpEAESNFY=,tag:BFzTcHODjHSxaMI+7Hxjog==,type:str]
    #ENC[AES256_GCM,data:F54YNpQW4LlTuYaFby5SeuR7,iv:2C8XP+yYfZyolfGs93KzdQsVEjfUrFHhfJKxsnT/jKo=,tag:fW7+LjbpM2V36G187f+4uA==,type:comment]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:6LvBnJRgumB5V/T9A+4z9lg5qq8vmY1E4kuXbvFiF4JLNpM7lOD3hv6IUUbzjKnfIpc=,iv:2GfnnoHEakxyfqu0IGugwhZxyJI7hunrUML4WFZf2iQ=,tag:DG90bI8qST63S3mb1TKv2Q==,type:str]
    AUTHENTIK_EMAIL_HOST: ENC[AES256_GCM,data:al3cABGaTbpcg5CxlbLBKmR65CU=,iv:iioJvXG5k5qyH/D7DuPu8BlpdRzQDQkdLbYNaZxkfEY=,tag:0gU6/eDHcPKapCHC9O4yaw==,type:str]
    AUTHENTIK_EMAIL_PORT: ENC[AES256_GCM,data:qIrU,iv:eXboJJg9FyoblMQ1RzdxUz1pRIjfuTESFA6qFM4dwX8=,tag:tl03FU/glZhhbvJuWfe/cQ==,type:str]
    AUTHENTIK_EMAIL_USERNAME: ENC[AES256_GCM,data:RK8EQngKZQhETMSew3SGXlc0YfkZvgo=,iv:UEsC8yQ3Z2w25EFwvonRVUlwfMb2Jf5iVjZOLs7jrUQ=,tag:rZ/fZahR6r/9aqJoNObpGQ==,type:str]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:FPuN0wLolxY5KPrWP5Qr3wOH,iv:3vrd3BPDjjJTrnmdPhAuZTZWT8ypCi90wd4a/g97EdQ=,tag:QK/njioNj4AXvMAJD6iufA==,type:str]
    AUTHENTIK_EMAIL_USE_TLS: ENC[AES256_GCM,data:nqq3f+E=,iv:OpEXDvkmvZUOgUIXrxFm2kTBgkDOsQyfDcEB6pEqYto=,tag:qSMnyY0Nn/7M5cIle43IRw==,type:str]
    AUTHENTIK_EMAIL_USE_SSL: ENC[AES256_GCM,data:766qiw==,iv:X5zlu7fd7/ayql/5niS67OZBnyYodsxRXzBMxJOhAME=,tag:fZi149cv1VOQmgDZVgF48w==,type:str]
    AUTHENTIK_EMAIL_TIMEOUT: ENC[AES256_GCM,data:xvU=,iv:7ll8kcP/7KrXyVdcCisQ6RMDsEZyUBE49WI0iAdAokQ=,tag:zAFT0YhpoN7FXJT8nTTXDw==,type:str]
    AUTHENTIK_EMAIL_FROM: ENC[AES256_GCM,data:p4ErG91RR25PtKDRKQD5mJfFM+mHts8=,iv:8ZY1C2i9YDqeitU/u5IFHCmhn+miDoo92Ptl5qJQ7xM=,tag:aANleWoG4m2jovgGMdRSGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxenBtWWZseUFRTUVieVpq
            cmdicUgvblZybWdUQVZCU2FHYmh5aWZocmh3CnVVbUdxaHNCMEV3YnVDYWZzNExi
            RGl4bWVDYzBXM3dWV3dHMXFLV1BCWlEKLS0tIDlFTk5DQ3pGYWRvdUF1ek9Nd0Rq
            NGJ4T1JuK0dwNDRocW9SSGFIbFI0M1kK8pEGI9RUQwT+Vr2q8Rb0GDYaFSz85mVL
            ATu/c8TFhVjxEjRdCl1Tt6DY72DKNt/Lq7KYQaFdn6XsFoCpkowpPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T03:14:39Z"
    mac: ENC[AES256_GCM,data:Q+BagHNA9p4pVLSmazMjk9V4B1mAZ4l8N74A4IGQe055z/5jz4vGbdUQov7MwqDKAym5WZjjRwWPC2lTmhP1Z+hYe9/gdugAFtYHMdujDyewNYmb/hBKtvVYsIG9yAF3obPN3RXkPipIdRoEEAe+QMOBOFzs4IyeM2Zz5Zz1UsY=,iv:qlI+bxTD+tAQ+3SvTLkfXsmf5QPSnp6v6RUP45tGuTY=,tag:QI4eO4hb2pPqGqYpEXqdig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
