---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-install-repo
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/fluxcd/flux2
  ref:
    tag: v0.38.3
  ignore: |
    /*
    !/manifests
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-install-repo
  images:
    - name: fluxcd/helm-controller
      newName: ghcr.io/fluxcd/helm-controller
    - name: fluxcd/image-automation-controller
      newName: ghcr.io/fluxcd/image-automation-controller
    - name: fluxcd/image-reflector-controller
      newName: ghcr.io/fluxcd/image-reflector-controller
    - name: fluxcd/kustomize-controller
      newName: ghcr.io/fluxcd/kustomize-controller
    - name: fluxcd/notification-controller
      newName: ghcr.io/fluxcd/notification-controller
    - name: fluxcd/source-controller
      newName: ghcr.io/fluxcd/source-controller
  patches:
    - patch: |-
        $patch: delete
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: not-used
      target:
        group: networking.k8s.io
        version: v1
        kind: NetworkPolicy
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --concurrent=20
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --requeue-dependency=5s
      target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller|source-controller)"
