---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app umami
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    fullNameOverride: *app
    image:
      repository: ghcr.io/umami-software/umami
      tag: postgresql-v2.3.0
    env:
      TIMEZONE: "${TZ}"
      DATABASE_TYPE: "postgresql"
      DATABASE_URL: "postgresql://postgres:${SECRET_POSTGRES_ADMIN_PASS}@postgresql.database.svc.cluster.local:5432/umami"
      DISABLE_TELEMETRY: "true"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/appName: Umami
          hajimari.io/icon: simple-icons:pleroma
          external-dns.alpha.kubernetes.io/target: "${CLOUDFLARE_DDNS_RECORD}"
        hosts:
          - host: &host "umami.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 15m
        memory: 25Mi
