---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-ingress-nginx-certificates
  namespace: flux-system
spec:
  path: ./cluster/core/networking/ingress-nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-core-cert-manager-issuers
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 20m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-core-ingress-nginx-certificates
  path: ./cluster/core/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: ingress-nginx
      namespace: networking
  interval: 30m
  retryInterval: 1m
  timeout: 20m
