---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.23
      sourceRef:
        kind: HelmRepository
        name: chart-weave
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "$2a$12$ru.vLaI.rACBD.urAEiqbOddY.tLj6DRqpVB1m.KC.b.KEkMhJfwm"
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/appName: Weave GitOps
        hajimari.io/icon: material-symbols:health-metrics
      hosts:
        - host: &host "gitops.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      impersonationResourceNames: ["admin"]
