apiVersion: v1
kind: Secret
metadata:
    name: radarr-apikey
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:smXMIvPE+olhMZQfLgpuKVLzhMUFKZZcJMX0jq+hZ+kXf2kX,iv:FgjN1ziLGE9zjLL/SYuges27P99SZo/uWYsOP7FndEA=,tag:HTJoFuJhRMip31b3a5KbQg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a2c3lk7m069m3mtumw582zjyjaxgev9es7n3yk4phvyd63crxedsnu3agc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTndNSlVYTFZOU1htbyt2
            RDdkUmc0Y0xxK1dheUhJbWZvdFJJMTFlcUNVClVjTlN4dEprK3FMZmhGRGNscWtB
            YTFLejhOOHlaYjVNNGJEaGhUYTRySVUKLS0tIDFSM01BWFBJbytObHk4L1RzNVBr
            dlA2ZGxxRHBhZUVGeHN1SklkRlM3c3cK3/EvgaNiRSOEmo69/H/H4MDWdqGNsZeS
            DyRLBl86/gSI0NfL6zs7YnGKEDPrt5ci6bH4ZMzEuSg8bpVsZXk9RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-12T19:27:59Z"
    mac: ENC[AES256_GCM,data:yv6DzcfJc9Jz7E7u2pg6MTkIYGd67dD+sG1JwYffgVgPCYOaNaGtT8+Fv1NjpQQthjsGCrMo3Rz3QPe0d652sQiTicAv09VEyQi8KWPo2EPVmuRD5VPD6PVnpnhoVQDDrprSw9f80wcE0dI/85KtpltSvrAB3nItsj45UsZ+uYQ=,iv:U7HYb3t68bUTAds/mLym7PjIylwrjL2vRgBKHwFEIHA=,tag:J51SzRPykPtdtm2A7S8L4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
