---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.733
    envFrom:
      - secretRef:
          name: sonarr-apikey
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Sonarr
          hajimari.io/icon: gala:tv
          nginx.ingress.kubernetes.io/auth-url: |-
            http://authentik.security.svc.cluster.local/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://sso.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [568]
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
      media:
        enabled: true
        mountPath: /media
        path: "${STORAGE_NAS_MEDIA_PATH}"
        server: "${STORAGE_NAS_IP}"
        type: nfs
