---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: chart-bjw
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: postgresql
      namespace: database
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.0.535
    envFrom:
      - secretRef:
          name: sonarr-apikey
    env:
      TZ: ${TIMEZONE}
      SONARR__LOG_LEVEL: info
      SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
      SONARR__POSTGRES_HOST: "postgresql.database.svc.cluster.local"
      SONARR__POSTGRES_USER: "postgres"
      SONARR__POSTGRES_PASSWORD: "${SECRET_POSTGRES_ADMIN_PASS}"
      SONARR__POSTGRES_MAIN_DB: sonarr
      SONARR__POSTGRES_LOG_DB: sonarr-logs
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: Sonarr
          hajimari.io/icon: gala:tv
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
      api:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: *host
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [568]
    persistence:
      media:
        enabled: true
        mountPath: /media
        path: "${STORAGE_NAS_MEDIA_PATH}"
        server: "${STORAGE_NAS_IP}"
        type: nfs
