---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  timeout: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 44.3.1
      sourceRef:
        kind: HelmRepository
        name: chart-prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 5
      remediateLastFailure: true
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    kubeControllerManager:
      enabled: true
      endpoints: ["192.168.1.10", "192.168.1.11", "192.168.1.12"]
    kubeScheduler:
      enabled: true
      endpoints: ["192.168.1.10", "192.168.1.11", "192.168.1.12"]
    coreDns:
      enabled: true
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeDns:
      enabled: false
    kubeApiServer:
      enabled: false
    grafana:
      enabled: false
      forceDeployDashboards: true
    nodeExporter:
      enabled: true
    prometheusOperator:
      resources:
        requests:
          cpu: 15m
          memory: 110M
        limits:
          cpu: 15m
          memory: 110M
    prometheus-node-exporter:
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          cpu: 15m
          memory: 105M
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels:
                - __meta_kubernetes_pod_node_name
              targetLabel: kubernetes_node
    prometheus:
      ingress:
        enabled: true
        ingressClassName: nginx
        pathType: Prefix
        annotations:
          hajimari.io/appName: Prometheus
          hajimari.io/icon: simple-icons:prometheus
        hosts:
          - prometheus.${SECRET_LAN_DOMAIN}
      prometheusSpec:
        enableAdminAPI: true
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        walCompression: true
        retention: 10d
        retentionSize: "8GB"
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "Alert Manager"
          hajimari.io/icon: mdi:alert-decagram-outline
        hosts:
          - alertmanager.${SECRET_LAN_DOMAIN}
      alertmanagerSpec:
        resources:
          requests:
            cpu: 11m
            memory: 53M
          limits:
            cpu: 11m
            memory: 53M
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              resources:
                requests:
                  storage: 1Gi
