---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: chart-ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  values:
    controller:
      ingressClass: nginx
      replicaCount: 1
      service:
        type: LoadBalancer
        loadBalancerIP: ${NIGNX_INGRESS_IP}
        externalIPs:
          - ${NIGNX_INGRESS_IP}
        externalTrafficPolicy: Local
      config:
        ssl-protocols: TLSv1.3 TLSv1.2
        proxy-body-size: 100m
        use-forwarded-headers: 'true'
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      resources:
        requests:
          memory: 100Mi
          cpu: 100m
        limits:
          memory: 500Mi
