---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - qbittorrent
  - sabnzbd
  - sonarr
  - radarr
  - bazarr
  - prowlarr
  - recyclarr
  - flaresolverr
  - jellyseerr
