---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.7.2
      sourceRef:
        kind: HelmRepository
        name: chart-external-secrets
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
