---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
