---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: influxdb
      version: 4.12.5
      sourceRef:
        kind: HelmRepository
        name: chart-influxdata
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: longhorn
      namespace: longhorn-system
  values:
    image:
      repository: "influxdb"
      tag: "1.8.10-alpine"
      pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${INFLUXDB_LB_IP}"
      externalIPs: ["${INFLUXDB_LB_IP}"]
      externalTrafficPolicy: Local
    setDefaultUser:
      enabled: true
      user:
        username: "admin"
        password: "${SECRET_INFLUXDB_ADMIN_PASS}"
    persistence:
      enabled: true
      existingClaim: influxdb-data
      name: influxdb-data
    ingress:
      enabled: false
